services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U turnero_user -d turnero_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: ghcr.io/gabriellaniado/ingsoft3-tp01-backend:v0.1.0
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/gabriellaniado/ingsoft3-tp01-frontend:v0.1.0
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
